### ISSUE TITLE
mvn package failing on echo example

### ISSUE THREAD

**Issue by yswu** [twitter/iago#35]
y@local:~/workspace/iago/examples/echo{master} $ mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building iago-echo 1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-finagle-thrift-plugin:0.0.9:compile (thrift-sources) @ iago-echo ---
[INFO] Generated thrift files up to date, skipping compile.
[INFO]
[INFO] --- maven-build-properties-plugin:0.0.2:compile (default) @ iago-echo ---
[INFO] writing build properties to /Users/y/workspace/iago/examples/echo/target/generated-resources/com/twitter/iago-echo/build.properties
[INFO] 	version: 1.0
[INFO] 	build_branch_name: refs/heads/master
[INFO] 	build_revision: f52d586c06f11a1897c55e26f5670d5c803ad3a9
[INFO] 	name: iago-echo
[INFO] 	build_name: 20141004-021134
[INFO] 	build_last_few_commits: f52d586 (HEAD, origin/master, origin/HEAD, master) Merge pull request #34 from madster26/patch-1
1a30fa4 Fix bug in ParrotCluster shutdown
82db1ba Merge pull request #33 from eliocapelati/patch-1
4ac838d Just a small fix on README
520696d Merge pull request #32 from jwstric2/master
ac4ca1c Added PUT support.  Request body supported added for PUT as it will contain a newly-updated representation of an original resource or even possibly a new resource.
01d69ed Merge pull request #27 from ExpediaInc/xforwardedfor
f153d80 Merge pull request #29 from fedeoasi/double-bracket
d41612b Use single brackets instead of double in common.sh
d8308fd didn't realize package-dist was not release so including a copy here
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ iago-echo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/y/workspace/iago/examples/echo/src/main/resources
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO] Copying 1 resource
[INFO]
[INFO] --- scala-maven-plugin:3.0.1:add-source (scala-compile-first) @ iago-echo ---
[INFO] Add Source directory: /Users/y/workspace/iago/examples/echo/src/main/scala
[INFO] Add Test Source directory: /Users/y/workspace/iago/examples/echo/src/test/scala
[INFO]
[INFO] --- scala-maven-plugin:3.0.1:compile (scala-compile-first) @ iago-echo ---
[INFO] Checking for multiple versions of scala
[WARNING]  Expected all dependencies to require Scala version: 2.9.2
[WARNING]  com.twitter:iago:0.6.14 requires scala version: 2.10.3
[WARNING] Multiple versions of scala libraries detected!
[INFO] includes = [**/*.scala,**/*.java,]
[INFO] excludes = []
[INFO] /Users/y/workspace/iago/examples/echo/src/main/java:-1: info: compiling
[INFO] /Users/y/workspace/iago/examples/echo/target/generated-sources/thrift/gen-java:-1: info: compiling
[INFO] /Users/y/workspace/iago/examples/echo/src/main/scala:-1: info: compiling
[INFO] Compiling 5 source files to /Users/y/workspace/iago/examples/echo/target/classes at 1412413895641
[ERROR] error: error while loading Await, class file needed by Await is missing.
[INFO] reference type InterruptedException of object package refers to nonexisting symbol.
[ERROR] error: error while loading Awaitable, class file needed by Awaitable is missing.
[INFO] reference type InterruptedException of object package refers to nonexisting symbol.
[ERROR] two errors found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.985 s
[INFO] Finished at: 2014-10-04T02:11:38-07:00
[INFO] Final Memory: 10M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.0.1:compile (scala-compile-first) on project iago-echo: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by WamBamBoozle** [comment]
Thanks for the patch raphaelfeng
